name: Complete Codeforces mission

on:
  workflow_dispatch:

jobs:
  update-chrome:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Google Chrome installer
        run: Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/latest/chrome_installer.exe" -OutFile "chrome_installer.exe"
        
      - name: Install/Update Google Chrome
        run: .\chrome_installer.exe /silent /install

      - name: Run exe
        run: ./output/main.exe